// Structured country data - EN/CN names, capitals, flags, regions
// Easily extensible with custom fields
const COUNTRY_DATA = {
  "AFG": { name_en: "Afghanistan", name_cn: "阿富汗", capital_en: "Kabul", capital_cn: "喀布尔", region_en: "Asia", region_cn: "亚洲", subregion_en: "Southern Asia", subregion_cn: "南亚", flag: "🇦🇫" },
  "ALB": { name_en: "Albania", name_cn: "阿尔巴尼亚", capital_en: "Tirana", capital_cn: "地拉那", region_en: "Europe", region_cn: "欧洲", subregion_en: "Southern Europe", subregion_cn: "南欧", flag: "🇦🇱" },
  "DZA": { name_en: "Algeria", name_cn: "阿尔及利亚", capital_en: "Algiers", capital_cn: "阿尔及尔", region_en: "Africa", region_cn: "非洲", subregion_en: "Northern Africa", subregion_cn: "北非", flag: "🇩🇿" },
  "AGO": { name_en: "Angola", name_cn: "安哥拉", capital_en: "Luanda", capital_cn: "罗安达", region_en: "Africa", region_cn: "非洲", subregion_en: "Middle Africa", subregion_cn: "中非", flag: "🇦🇴" },
  "ARG": { name_en: "Argentina", name_cn: "阿根廷", capital_en: "Buenos Aires", capital_cn: "布宜诺斯艾利斯", region_en: "South America", region_cn: "南美洲", subregion_en: "South America", subregion_cn: "南美", flag: "🇦🇷" },
  "ARM": { name_en: "Armenia", name_cn: "亚美尼亚", capital_en: "Yerevan", capital_cn: "埃里温", region_en: "Asia", region_cn: "亚洲", subregion_en: "Western Asia", subregion_cn: "西亚", flag: "🇦🇲" },
  "AUS": { name_en: "Australia", name_cn: "澳大利亚", capital_en: "Canberra", capital_cn: "堪培拉", region_en: "Oceania", region_cn: "大洋洲", subregion_en: "Australia and New Zealand", subregion_cn: "澳新", flag: "🇦🇺" },
  "AUT": { name_en: "Austria", name_cn: "奥地利", capital_en: "Vienna", capital_cn: "维也纳", region_en: "Europe", region_cn: "欧洲", subregion_en: "Western Europe", subregion_cn: "西欧", flag: "🇦🇹" },
  "AZE": { name_en: "Azerbaijan", name_cn: "阿塞拜疆", capital_en: "Baku", capital_cn: "巴库", region_en: "Asia", region_cn: "亚洲", subregion_en: "Western Asia", subregion_cn: "西亚", flag: "🇦🇿" },
  "BGD": { name_en: "Bangladesh", name_cn: "孟加拉国", capital_en: "Dhaka", capital_cn: "达卡", region_en: "Asia", region_cn: "亚洲", subregion_en: "Southern Asia", subregion_cn: "南亚", flag: "🇧🇩" },
  "BLR": { name_en: "Belarus", name_cn: "白俄罗斯", capital_en: "Minsk", capital_cn: "明斯克", region_en: "Europe", region_cn: "欧洲", subregion_en: "Eastern Europe", subregion_cn: "东欧", flag: "🇧🇾" },
  "BEL": { name_en: "Belgium", name_cn: "比利时", capital_en: "Brussels", capital_cn: "布鲁塞尔", region_en: "Europe", region_cn: "欧洲", subregion_en: "Western Europe", subregion_cn: "西欧", flag: "🇧🇪" },
  "BEN": { name_en: "Benin", name_cn: "贝宁", capital_en: "Porto-Novo", capital_cn: "波多诺伏", region_en: "Africa", region_cn: "非洲", subregion_en: "Western Africa", subregion_cn: "西非", flag: "🇧🇯" },
  "BTN": { name_en: "Bhutan", name_cn: "不丹", capital_en: "Thimphu", capital_cn: "廷布", region_en: "Asia", region_cn: "亚洲", subregion_en: "Southern Asia", subregion_cn: "南亚", flag: "🇧🇹" },
  "BOL": { name_en: "Bolivia", name_cn: "玻利维亚", capital_en: "La Paz", capital_cn: "拉巴斯", region_en: "South America", region_cn: "南美洲", subregion_en: "South America", subregion_cn: "南美", flag: "🇧🇴" },
  "BIH": { name_en: "Bosnia and Herz.", name_cn: "波黑", capital_en: "Sarajevo", capital_cn: "萨拉热窝", region_en: "Europe", region_cn: "欧洲", subregion_en: "Southern Europe", subregion_cn: "南欧", flag: "🇧🇦" },
  "BWA": { name_en: "Botswana", name_cn: "博茨瓦纳", capital_en: "Gaborone", capital_cn: "哈博罗内", region_en: "Africa", region_cn: "非洲", subregion_en: "Southern Africa", subregion_cn: "南非", flag: "🇧🇼" },
  "BRA": { name_en: "Brazil", name_cn: "巴西", capital_en: "Brasilia", capital_cn: "巴西利亚", region_en: "South America", region_cn: "南美洲", subregion_en: "South America", subregion_cn: "南美", flag: "🇧🇷" },
  "BRN": { name_en: "Brunei", name_cn: "文莱", capital_en: "Bandar Seri Begawan", capital_cn: "斯里巴加湾", region_en: "Asia", region_cn: "亚洲", subregion_en: "South-Eastern Asia", subregion_cn: "东南亚", flag: "🇧🇳" },
  "BGR": { name_en: "Bulgaria", name_cn: "保加利亚", capital_en: "Sofia", capital_cn: "索菲亚", region_en: "Europe", region_cn: "欧洲", subregion_en: "Eastern Europe", subregion_cn: "东欧", flag: "🇧🇬" },
  "BFA": { name_en: "Burkina Faso", name_cn: "布基纳法索", capital_en: "Ouagadougou", capital_cn: "瓦加杜古", region_en: "Africa", region_cn: "非洲", subregion_en: "Western Africa", subregion_cn: "西非", flag: "🇧🇫" },
  "BDI": { name_en: "Burundi", name_cn: "布隆迪", capital_en: "Gitega", capital_cn: "基特加", region_en: "Africa", region_cn: "非洲", subregion_en: "Eastern Africa", subregion_cn: "东非", flag: "🇧🇮" },
  "KHM": { name_en: "Cambodia", name_cn: "柬埔寨", capital_en: "Phnom Penh", capital_cn: "金边", region_en: "Asia", region_cn: "亚洲", subregion_en: "South-Eastern Asia", subregion_cn: "东南亚", flag: "🇰🇭" },
  "CMR": { name_en: "Cameroon", name_cn: "喀麦隆", capital_en: "Yaounde", capital_cn: "雅温得", region_en: "Africa", region_cn: "非洲", subregion_en: "Middle Africa", subregion_cn: "中非", flag: "🇨🇲" },
  "CAN": { name_en: "Canada", name_cn: "加拿大", capital_en: "Ottawa", capital_cn: "渥太华", region_en: "North America", region_cn: "北美洲", subregion_en: "Northern America", subregion_cn: "北美", flag: "🇨🇦" },
  "CAF": { name_en: "Central African Rep.", name_cn: "中非共和国", capital_en: "Bangui", capital_cn: "班吉", region_en: "Africa", region_cn: "非洲", subregion_en: "Middle Africa", subregion_cn: "中非", flag: "🇨🇫" },
  "TCD": { name_en: "Chad", name_cn: "乍得", capital_en: "N'Djamena", capital_cn: "恩贾梅纳", region_en: "Africa", region_cn: "非洲", subregion_en: "Middle Africa", subregion_cn: "中非", flag: "🇹🇩" },
  "CHL": { name_en: "Chile", name_cn: "智利", capital_en: "Santiago", capital_cn: "圣地亚哥", region_en: "South America", region_cn: "南美洲", subregion_en: "South America", subregion_cn: "南美", flag: "🇨🇱" },
  "CHN": { name_en: "China", name_cn: "中国", capital_en: "Beijing", capital_cn: "北京", region_en: "Asia", region_cn: "亚洲", subregion_en: "Eastern Asia", subregion_cn: "东亚", flag: "🇨🇳" },
  "COL": { name_en: "Colombia", name_cn: "哥伦比亚", capital_en: "Bogota", capital_cn: "波哥大", region_en: "South America", region_cn: "南美洲", subregion_en: "South America", subregion_cn: "南美", flag: "🇨🇴" },
  "COD": { name_en: "Dem. Rep. Congo", name_cn: "刚果(金)", capital_en: "Kinshasa", capital_cn: "金沙萨", region_en: "Africa", region_cn: "非洲", subregion_en: "Middle Africa", subregion_cn: "中非", flag: "🇨🇩" },
  "COG": { name_en: "Congo", name_cn: "刚果(布)", capital_en: "Brazzaville", capital_cn: "布拉柴维尔", region_en: "Africa", region_cn: "非洲", subregion_en: "Middle Africa", subregion_cn: "中非", flag: "🇨🇬" },
  "CRI": { name_en: "Costa Rica", name_cn: "哥斯达黎加", capital_en: "San Jose", capital_cn: "圣何塞", region_en: "North America", region_cn: "北美洲", subregion_en: "Central America", subregion_cn: "中美", flag: "🇨🇷" },
  "CIV": { name_en: "Cote d'Ivoire", name_cn: "科特迪瓦", capital_en: "Yamoussoukro", capital_cn: "亚穆苏克罗", region_en: "Africa", region_cn: "非洲", subregion_en: "Western Africa", subregion_cn: "西非", flag: "🇨🇮" },
  "HRV": { name_en: "Croatia", name_cn: "克罗地亚", capital_en: "Zagreb", capital_cn: "萨格勒布", region_en: "Europe", region_cn: "欧洲", subregion_en: "Southern Europe", subregion_cn: "南欧", flag: "🇭🇷" },
  "CUB": { name_en: "Cuba", name_cn: "古巴", capital_en: "Havana", capital_cn: "哈瓦那", region_en: "North America", region_cn: "北美洲", subregion_en: "Caribbean", subregion_cn: "加勒比", flag: "🇨🇺" },
  "CYP": { name_en: "Cyprus", name_cn: "塞浦路斯", capital_en: "Nicosia", capital_cn: "尼科西亚", region_en: "Asia", region_cn: "亚洲", subregion_en: "Western Asia", subregion_cn: "西亚", flag: "🇨🇾" },
  "CZE": { name_en: "Czechia", name_cn: "捷克", capital_en: "Prague", capital_cn: "布拉格", region_en: "Europe", region_cn: "欧洲", subregion_en: "Eastern Europe", subregion_cn: "东欧", flag: "🇨🇿" },
  "DNK": { name_en: "Denmark", name_cn: "丹麦", capital_en: "Copenhagen", capital_cn: "哥本哈根", region_en: "Europe", region_cn: "欧洲", subregion_en: "Northern Europe", subregion_cn: "北欧", flag: "🇩🇰" },
  "DJI": { name_en: "Djibouti", name_cn: "吉布提", capital_en: "Djibouti", capital_cn: "吉布提", region_en: "Africa", region_cn: "非洲", subregion_en: "Eastern Africa", subregion_cn: "东非", flag: "🇩🇯" },
  "DOM": { name_en: "Dominican Rep.", name_cn: "多米尼加", capital_en: "Santo Domingo", capital_cn: "圣多明各", region_en: "North America", region_cn: "北美洲", subregion_en: "Caribbean", subregion_cn: "加勒比", flag: "🇩🇴" },
  "ECU": { name_en: "Ecuador", name_cn: "厄瓜多尔", capital_en: "Quito", capital_cn: "基多", region_en: "South America", region_cn: "南美洲", subregion_en: "South America", subregion_cn: "南美", flag: "🇪🇨" },
  "EGY": { name_en: "Egypt", name_cn: "埃及", capital_en: "Cairo", capital_cn: "开罗", region_en: "Africa", region_cn: "非洲", subregion_en: "Northern Africa", subregion_cn: "北非", flag: "🇪🇬" },
  "SLV": { name_en: "El Salvador", name_cn: "萨尔瓦多", capital_en: "San Salvador", capital_cn: "圣萨尔瓦多", region_en: "North America", region_cn: "北美洲", subregion_en: "Central America", subregion_cn: "中美", flag: "🇸🇻" },
  "GNQ": { name_en: "Eq. Guinea", name_cn: "赤道几内亚", capital_en: "Malabo", capital_cn: "马拉博", region_en: "Africa", region_cn: "非洲", subregion_en: "Middle Africa", subregion_cn: "中非", flag: "🇬🇶" },
  "ERI": { name_en: "Eritrea", name_cn: "厄立特里亚", capital_en: "Asmara", capital_cn: "阿斯马拉", region_en: "Africa", region_cn: "非洲", subregion_en: "Eastern Africa", subregion_cn: "东非", flag: "🇪🇷" },
  "EST": { name_en: "Estonia", name_cn: "爱沙尼亚", capital_en: "Tallinn", capital_cn: "塔林", region_en: "Europe", region_cn: "欧洲", subregion_en: "Northern Europe", subregion_cn: "北欧", flag: "🇪🇪" },
  "SWZ": { name_en: "eSwatini", name_cn: "斯威士兰", capital_en: "Mbabane", capital_cn: "姆巴巴内", region_en: "Africa", region_cn: "非洲", subregion_en: "Southern Africa", subregion_cn: "南非", flag: "🇸🇿" },
  "ETH": { name_en: "Ethiopia", name_cn: "埃塞俄比亚", capital_en: "Addis Ababa", capital_cn: "亚的斯亚贝巴", region_en: "Africa", region_cn: "非洲", subregion_en: "Eastern Africa", subregion_cn: "东非", flag: "🇪🇹" },
  "FJI": { name_en: "Fiji", name_cn: "斐济", capital_en: "Suva", capital_cn: "苏瓦", region_en: "Oceania", region_cn: "大洋洲", subregion_en: "Melanesia", subregion_cn: "美拉尼西亚", flag: "🇫🇯" },
  "FIN": { name_en: "Finland", name_cn: "芬兰", capital_en: "Helsinki", capital_cn: "赫尔辛基", region_en: "Europe", region_cn: "欧洲", subregion_en: "Northern Europe", subregion_cn: "北欧", flag: "🇫🇮" },
  "FRA": { name_en: "France", name_cn: "法国", capital_en: "Paris", capital_cn: "巴黎", region_en: "Europe", region_cn: "欧洲", subregion_en: "Western Europe", subregion_cn: "西欧", flag: "🇫🇷" },
  "GAB": { name_en: "Gabon", name_cn: "加蓬", capital_en: "Libreville", capital_cn: "利伯维尔", region_en: "Africa", region_cn: "非洲", subregion_en: "Middle Africa", subregion_cn: "中非", flag: "🇬🇦" },
  "GMB": { name_en: "Gambia", name_cn: "冈比亚", capital_en: "Banjul", capital_cn: "班珠尔", region_en: "Africa", region_cn: "非洲", subregion_en: "Western Africa", subregion_cn: "西非", flag: "🇬🇲" },
  "GEO": { name_en: "Georgia", name_cn: "格鲁吉亚", capital_en: "Tbilisi", capital_cn: "第比利斯", region_en: "Asia", region_cn: "亚洲", subregion_en: "Western Asia", subregion_cn: "西亚", flag: "🇬🇪" },
  "DEU": { name_en: "Germany", name_cn: "德国", capital_en: "Berlin", capital_cn: "柏林", region_en: "Europe", region_cn: "欧洲", subregion_en: "Western Europe", subregion_cn: "西欧", flag: "🇩🇪" },
  "GHA": { name_en: "Ghana", name_cn: "加纳", capital_en: "Accra", capital_cn: "阿克拉", region_en: "Africa", region_cn: "非洲", subregion_en: "Western Africa", subregion_cn: "西非", flag: "🇬🇭" },
  "GRC": { name_en: "Greece", name_cn: "希腊", capital_en: "Athens", capital_cn: "雅典", region_en: "Europe", region_cn: "欧洲", subregion_en: "Southern Europe", subregion_cn: "南欧", flag: "🇬🇷" },
  "GRL": { name_en: "Greenland", name_cn: "格陵兰", capital_en: "Nuuk", capital_cn: "努克", region_en: "North America", region_cn: "北美洲", subregion_en: "Northern America", subregion_cn: "北美", flag: "🇬🇱" },
  "GTM": { name_en: "Guatemala", name_cn: "危地马拉", capital_en: "Guatemala City", capital_cn: "危地马拉城", region_en: "North America", region_cn: "北美洲", subregion_en: "Central America", subregion_cn: "中美", flag: "🇬🇹" },
  "GIN": { name_en: "Guinea", name_cn: "几内亚", capital_en: "Conakry", capital_cn: "科纳克里", region_en: "Africa", region_cn: "非洲", subregion_en: "Western Africa", subregion_cn: "西非", flag: "🇬🇳" },
  "GNB": { name_en: "Guinea-Bissau", name_cn: "几内亚比绍", capital_en: "Bissau", capital_cn: "比绍", region_en: "Africa", region_cn: "非洲", subregion_en: "Western Africa", subregion_cn: "西非", flag: "🇬🇼" },
  "GUY": { name_en: "Guyana", name_cn: "圭亚那", capital_en: "Georgetown", capital_cn: "乔治敦", region_en: "South America", region_cn: "南美洲", subregion_en: "South America", subregion_cn: "南美", flag: "🇬🇾" },
  "HTI": { name_en: "Haiti", name_cn: "海地", capital_en: "Port-au-Prince", capital_cn: "太子港", region_en: "North America", region_cn: "北美洲", subregion_en: "Caribbean", subregion_cn: "加勒比", flag: "🇭🇹" },
  "HND": { name_en: "Honduras", name_cn: "洪都拉斯", capital_en: "Tegucigalpa", capital_cn: "特古西加尔巴", region_en: "North America", region_cn: "北美洲", subregion_en: "Central America", subregion_cn: "中美", flag: "🇭🇳" },
  "HUN": { name_en: "Hungary", name_cn: "匈牙利", capital_en: "Budapest", capital_cn: "布达佩斯", region_en: "Europe", region_cn: "欧洲", subregion_en: "Eastern Europe", subregion_cn: "东欧", flag: "🇭🇺" },
  "ISL": { name_en: "Iceland", name_cn: "冰岛", capital_en: "Reykjavik", capital_cn: "雷克雅未克", region_en: "Europe", region_cn: "欧洲", subregion_en: "Northern Europe", subregion_cn: "北欧", flag: "🇮🇸" },
  "IND": { name_en: "India", name_cn: "印度", capital_en: "New Delhi", capital_cn: "新德里", region_en: "Asia", region_cn: "亚洲", subregion_en: "Southern Asia", subregion_cn: "南亚", flag: "🇮🇳" },
  "IDN": { name_en: "Indonesia", name_cn: "印度尼西亚", capital_en: "Jakarta", capital_cn: "雅加达", region_en: "Asia", region_cn: "亚洲", subregion_en: "South-Eastern Asia", subregion_cn: "东南亚", flag: "🇮🇩" },
  "IRN": { name_en: "Iran", name_cn: "伊朗", capital_en: "Tehran", capital_cn: "德黑兰", region_en: "Asia", region_cn: "亚洲", subregion_en: "Southern Asia", subregion_cn: "南亚", flag: "🇮🇷" },
  "IRQ": { name_en: "Iraq", name_cn: "伊拉克", capital_en: "Baghdad", capital_cn: "巴格达", region_en: "Asia", region_cn: "亚洲", subregion_en: "Western Asia", subregion_cn: "西亚", flag: "🇮🇶" },
  "IRL": { name_en: "Ireland", name_cn: "爱尔兰", capital_en: "Dublin", capital_cn: "都柏林", region_en: "Europe", region_cn: "欧洲", subregion_en: "Northern Europe", subregion_cn: "北欧", flag: "🇮🇪" },
  "ISR": { name_en: "Israel", name_cn: "以色列", capital_en: "Jerusalem", capital_cn: "耶路撒冷", region_en: "Asia", region_cn: "亚洲", subregion_en: "Western Asia", subregion_cn: "西亚", flag: "🇮🇱" },
  "ITA": { name_en: "Italy", name_cn: "意大利", capital_en: "Rome", capital_cn: "罗马", region_en: "Europe", region_cn: "欧洲", subregion_en: "Southern Europe", subregion_cn: "南欧", flag: "🇮🇹" },
  "JAM": { name_en: "Jamaica", name_cn: "牙买加", capital_en: "Kingston", capital_cn: "金斯敦", region_en: "North America", region_cn: "北美洲", subregion_en: "Caribbean", subregion_cn: "加勒比", flag: "🇯🇲" },
  "JPN": { name_en: "Japan", name_cn: "日本", capital_en: "Tokyo", capital_cn: "东京", region_en: "Asia", region_cn: "亚洲", subregion_en: "Eastern Asia", subregion_cn: "东亚", flag: "🇯🇵" },
  "JOR": { name_en: "Jordan", name_cn: "约旦", capital_en: "Amman", capital_cn: "安曼", region_en: "Asia", region_cn: "亚洲", subregion_en: "Western Asia", subregion_cn: "西亚", flag: "🇯🇴" },
  "KAZ": { name_en: "Kazakhstan", name_cn: "哈萨克斯坦", capital_en: "Astana", capital_cn: "阿斯塔纳", region_en: "Asia", region_cn: "亚洲", subregion_en: "Central Asia", subregion_cn: "中亚", flag: "🇰🇿" },
  "KEN": { name_en: "Kenya", name_cn: "肯尼亚", capital_en: "Nairobi", capital_cn: "内罗毕", region_en: "Africa", region_cn: "非洲", subregion_en: "Eastern Africa", subregion_cn: "东非", flag: "🇰🇪" },
  "PRK": { name_en: "North Korea", name_cn: "朝鲜", capital_en: "Pyongyang", capital_cn: "平壤", region_en: "Asia", region_cn: "亚洲", subregion_en: "Eastern Asia", subregion_cn: "东亚", flag: "🇰🇵" },
  "KOR": { name_en: "South Korea", name_cn: "韩国", capital_en: "Seoul", capital_cn: "首尔", region_en: "Asia", region_cn: "亚洲", subregion_en: "Eastern Asia", subregion_cn: "东亚", flag: "🇰🇷" },
  "KWT": { name_en: "Kuwait", name_cn: "科威特", capital_en: "Kuwait City", capital_cn: "科威特城", region_en: "Asia", region_cn: "亚洲", subregion_en: "Western Asia", subregion_cn: "西亚", flag: "🇰🇼" },
  "KGZ": { name_en: "Kyrgyzstan", name_cn: "吉尔吉斯斯坦", capital_en: "Bishkek", capital_cn: "比什凯克", region_en: "Asia", region_cn: "亚洲", subregion_en: "Central Asia", subregion_cn: "中亚", flag: "🇰🇬" },
  "LAO": { name_en: "Laos", name_cn: "老挝", capital_en: "Vientiane", capital_cn: "万象", region_en: "Asia", region_cn: "亚洲", subregion_en: "South-Eastern Asia", subregion_cn: "东南亚", flag: "🇱🇦" },
  "LVA": { name_en: "Latvia", name_cn: "拉脱维亚", capital_en: "Riga", capital_cn: "里加", region_en: "Europe", region_cn: "欧洲", subregion_en: "Northern Europe", subregion_cn: "北欧", flag: "🇱🇻" },
  "LBN": { name_en: "Lebanon", name_cn: "黎巴嫩", capital_en: "Beirut", capital_cn: "贝鲁特", region_en: "Asia", region_cn: "亚洲", subregion_en: "Western Asia", subregion_cn: "西亚", flag: "🇱🇧" },
  "LSO": { name_en: "Lesotho", name_cn: "莱索托", capital_en: "Maseru", capital_cn: "马塞卢", region_en: "Africa", region_cn: "非洲", subregion_en: "Southern Africa", subregion_cn: "南非", flag: "🇱🇸" },
  "LBR": { name_en: "Liberia", name_cn: "利比里亚", capital_en: "Monrovia", capital_cn: "蒙罗维亚", region_en: "Africa", region_cn: "非洲", subregion_en: "Western Africa", subregion_cn: "西非", flag: "🇱🇷" },
  "LBY": { name_en: "Libya", name_cn: "利比亚", capital_en: "Tripoli", capital_cn: "的黎波里", region_en: "Africa", region_cn: "非洲", subregion_en: "Northern Africa", subregion_cn: "北非", flag: "🇱🇾" },
  "LTU": { name_en: "Lithuania", name_cn: "立陶宛", capital_en: "Vilnius", capital_cn: "维尔纽斯", region_en: "Europe", region_cn: "欧洲", subregion_en: "Northern Europe", subregion_cn: "北欧", flag: "🇱🇹" },
  "LUX": { name_en: "Luxembourg", name_cn: "卢森堡", capital_en: "Luxembourg", capital_cn: "卢森堡", region_en: "Europe", region_cn: "欧洲", subregion_en: "Western Europe", subregion_cn: "西欧", flag: "🇱🇺" },
  "MDG": { name_en: "Madagascar", name_cn: "马达加斯加", capital_en: "Antananarivo", capital_cn: "塔那那利佛", region_en: "Africa", region_cn: "非洲", subregion_en: "Eastern Africa", subregion_cn: "东非", flag: "🇲🇬" },
  "MWI": { name_en: "Malawi", name_cn: "马拉维", capital_en: "Lilongwe", capital_cn: "利隆圭", region_en: "Africa", region_cn: "非洲", subregion_en: "Eastern Africa", subregion_cn: "东非", flag: "🇲🇼" },
  "MYS": { name_en: "Malaysia", name_cn: "马来西亚", capital_en: "Kuala Lumpur", capital_cn: "吉隆坡", region_en: "Asia", region_cn: "亚洲", subregion_en: "South-Eastern Asia", subregion_cn: "东南亚", flag: "🇲🇾" },
  "MLI": { name_en: "Mali", name_cn: "马里", capital_en: "Bamako", capital_cn: "巴马科", region_en: "Africa", region_cn: "非洲", subregion_en: "Western Africa", subregion_cn: "西非", flag: "🇲🇱" },
  "MRT": { name_en: "Mauritania", name_cn: "毛里塔尼亚", capital_en: "Nouakchott", capital_cn: "努瓦克肖特", region_en: "Africa", region_cn: "非洲", subregion_en: "Western Africa", subregion_cn: "西非", flag: "🇲🇷" },
  "MEX": { name_en: "Mexico", name_cn: "墨西哥", capital_en: "Mexico City", capital_cn: "墨西哥城", region_en: "North America", region_cn: "北美洲", subregion_en: "Central America", subregion_cn: "中美", flag: "🇲🇽" },
  "MDA": { name_en: "Moldova", name_cn: "摩尔多瓦", capital_en: "Chisinau", capital_cn: "基希讷乌", region_en: "Europe", region_cn: "欧洲", subregion_en: "Eastern Europe", subregion_cn: "东欧", flag: "🇲🇩" },
  "MNG": { name_en: "Mongolia", name_cn: "蒙古", capital_en: "Ulaanbaatar", capital_cn: "乌兰巴托", region_en: "Asia", region_cn: "亚洲", subregion_en: "Eastern Asia", subregion_cn: "东亚", flag: "🇲🇳" },
  "MNE": { name_en: "Montenegro", name_cn: "黑山", capital_en: "Podgorica", capital_cn: "波德戈里察", region_en: "Europe", region_cn: "欧洲", subregion_en: "Southern Europe", subregion_cn: "南欧", flag: "🇲🇪" },
  "MAR": { name_en: "Morocco", name_cn: "摩洛哥", capital_en: "Rabat", capital_cn: "拉巴特", region_en: "Africa", region_cn: "非洲", subregion_en: "Northern Africa", subregion_cn: "北非", flag: "🇲🇦" },
  "MOZ": { name_en: "Mozambique", name_cn: "莫桑比克", capital_en: "Maputo", capital_cn: "马普托", region_en: "Africa", region_cn: "非洲", subregion_en: "Eastern Africa", subregion_cn: "东非", flag: "🇲🇿" },
  "MMR": { name_en: "Myanmar", name_cn: "缅甸", capital_en: "Naypyidaw", capital_cn: "内比都", region_en: "Asia", region_cn: "亚洲", subregion_en: "South-Eastern Asia", subregion_cn: "东南亚", flag: "🇲🇲" },
  "NAM": { name_en: "Namibia", name_cn: "纳米比亚", capital_en: "Windhoek", capital_cn: "温得和克", region_en: "Africa", region_cn: "非洲", subregion_en: "Southern Africa", subregion_cn: "南非", flag: "🇳🇦" },
  "NPL": { name_en: "Nepal", name_cn: "尼泊尔", capital_en: "Kathmandu", capital_cn: "加德满都", region_en: "Asia", region_cn: "亚洲", subregion_en: "Southern Asia", subregion_cn: "南亚", flag: "🇳🇵" },
  "NLD": { name_en: "Netherlands", name_cn: "荷兰", capital_en: "Amsterdam", capital_cn: "阿姆斯特丹", region_en: "Europe", region_cn: "欧洲", subregion_en: "Western Europe", subregion_cn: "西欧", flag: "🇳🇱" },
  "NZL": { name_en: "New Zealand", name_cn: "新西兰", capital_en: "Wellington", capital_cn: "惠灵顿", region_en: "Oceania", region_cn: "大洋洲", subregion_en: "Australia and New Zealand", subregion_cn: "澳新", flag: "🇳🇿" },
  "NIC": { name_en: "Nicaragua", name_cn: "尼加拉瓜", capital_en: "Managua", capital_cn: "马那瓜", region_en: "North America", region_cn: "北美洲", subregion_en: "Central America", subregion_cn: "中美", flag: "🇳🇮" },
  "NER": { name_en: "Niger", name_cn: "尼日尔", capital_en: "Niamey", capital_cn: "尼亚美", region_en: "Africa", region_cn: "非洲", subregion_en: "Western Africa", subregion_cn: "西非", flag: "🇳🇪" },
  "NGA": { name_en: "Nigeria", name_cn: "尼日利亚", capital_en: "Abuja", capital_cn: "阿布贾", region_en: "Africa", region_cn: "非洲", subregion_en: "Western Africa", subregion_cn: "西非", flag: "🇳🇬" },
  "MKD": { name_en: "North Macedonia", name_cn: "北马其顿", capital_en: "Skopje", capital_cn: "斯科普里", region_en: "Europe", region_cn: "欧洲", subregion_en: "Southern Europe", subregion_cn: "南欧", flag: "🇲🇰" },
  "NOR": { name_en: "Norway", name_cn: "挪威", capital_en: "Oslo", capital_cn: "奥斯陆", region_en: "Europe", region_cn: "欧洲", subregion_en: "Northern Europe", subregion_cn: "北欧", flag: "🇳🇴" },
  "OMN": { name_en: "Oman", name_cn: "阿曼", capital_en: "Muscat", capital_cn: "马斯喀特", region_en: "Asia", region_cn: "亚洲", subregion_en: "Western Asia", subregion_cn: "西亚", flag: "🇴🇲" },
  "PAK": { name_en: "Pakistan", name_cn: "巴基斯坦", capital_en: "Islamabad", capital_cn: "伊斯兰堡", region_en: "Asia", region_cn: "亚洲", subregion_en: "Southern Asia", subregion_cn: "南亚", flag: "🇵🇰" },
  "PAN": { name_en: "Panama", name_cn: "巴拿马", capital_en: "Panama City", capital_cn: "巴拿马城", region_en: "North America", region_cn: "北美洲", subregion_en: "Central America", subregion_cn: "中美", flag: "🇵🇦" },
  "PNG": { name_en: "Papua New Guinea", name_cn: "巴布亚新几内亚", capital_en: "Port Moresby", capital_cn: "莫尔兹比港", region_en: "Oceania", region_cn: "大洋洲", subregion_en: "Melanesia", subregion_cn: "美拉尼西亚", flag: "🇵🇬" },
  "PRY": { name_en: "Paraguay", name_cn: "巴拉圭", capital_en: "Asuncion", capital_cn: "亚松森", region_en: "South America", region_cn: "南美洲", subregion_en: "South America", subregion_cn: "南美", flag: "🇵🇾" },
  "PER": { name_en: "Peru", name_cn: "秘鲁", capital_en: "Lima", capital_cn: "利马", region_en: "South America", region_cn: "南美洲", subregion_en: "South America", subregion_cn: "南美", flag: "🇵🇪" },
  "PHL": { name_en: "Philippines", name_cn: "菲律宾", capital_en: "Manila", capital_cn: "马尼拉", region_en: "Asia", region_cn: "亚洲", subregion_en: "South-Eastern Asia", subregion_cn: "东南亚", flag: "🇵🇭" },
  "POL": { name_en: "Poland", name_cn: "波兰", capital_en: "Warsaw", capital_cn: "华沙", region_en: "Europe", region_cn: "欧洲", subregion_en: "Eastern Europe", subregion_cn: "东欧", flag: "🇵🇱" },
  "PRT": { name_en: "Portugal", name_cn: "葡萄牙", capital_en: "Lisbon", capital_cn: "里斯本", region_en: "Europe", region_cn: "欧洲", subregion_en: "Southern Europe", subregion_cn: "南欧", flag: "🇵🇹" },
  "QAT": { name_en: "Qatar", name_cn: "卡塔尔", capital_en: "Doha", capital_cn: "多哈", region_en: "Asia", region_cn: "亚洲", subregion_en: "Western Asia", subregion_cn: "西亚", flag: "🇶🇦" },
  "ROU": { name_en: "Romania", name_cn: "罗马尼亚", capital_en: "Bucharest", capital_cn: "布加勒斯特", region_en: "Europe", region_cn: "欧洲", subregion_en: "Eastern Europe", subregion_cn: "东欧", flag: "🇷🇴" },
  "RUS": { name_en: "Russia", name_cn: "俄罗斯", capital_en: "Moscow", capital_cn: "莫斯科", region_en: "Europe", region_cn: "欧洲", subregion_en: "Eastern Europe", subregion_cn: "东欧", flag: "🇷🇺" },
  "RWA": { name_en: "Rwanda", name_cn: "卢旺达", capital_en: "Kigali", capital_cn: "基加利", region_en: "Africa", region_cn: "非洲", subregion_en: "Eastern Africa", subregion_cn: "东非", flag: "🇷🇼" },
  "SAU": { name_en: "Saudi Arabia", name_cn: "沙特阿拉伯", capital_en: "Riyadh", capital_cn: "利雅得", region_en: "Asia", region_cn: "亚洲", subregion_en: "Western Asia", subregion_cn: "西亚", flag: "🇸🇦" },
  "SEN": { name_en: "Senegal", name_cn: "塞内加尔", capital_en: "Dakar", capital_cn: "达喀尔", region_en: "Africa", region_cn: "非洲", subregion_en: "Western Africa", subregion_cn: "西非", flag: "🇸🇳" },
  "SRB": { name_en: "Serbia", name_cn: "塞尔维亚", capital_en: "Belgrade", capital_cn: "贝尔格莱德", region_en: "Europe", region_cn: "欧洲", subregion_en: "Southern Europe", subregion_cn: "南欧", flag: "🇷🇸" },
  "SLE": { name_en: "Sierra Leone", name_cn: "塞拉利昂", capital_en: "Freetown", capital_cn: "弗里敦", region_en: "Africa", region_cn: "非洲", subregion_en: "Western Africa", subregion_cn: "西非", flag: "🇸🇱" },
  "SGP": { name_en: "Singapore", name_cn: "新加坡", capital_en: "Singapore", capital_cn: "新加坡", region_en: "Asia", region_cn: "亚洲", subregion_en: "South-Eastern Asia", subregion_cn: "东南亚", flag: "🇸🇬" },
  "SVK": { name_en: "Slovakia", name_cn: "斯洛伐克", capital_en: "Bratislava", capital_cn: "布拉迪斯拉发", region_en: "Europe", region_cn: "欧洲", subregion_en: "Eastern Europe", subregion_cn: "东欧", flag: "🇸🇰" },
  "SVN": { name_en: "Slovenia", name_cn: "斯洛文尼亚", capital_en: "Ljubljana", capital_cn: "卢布尔雅那", region_en: "Europe", region_cn: "欧洲", subregion_en: "Southern Europe", subregion_cn: "南欧", flag: "🇸🇮" },
  "SLB": { name_en: "Solomon Is.", name_cn: "所罗门群岛", capital_en: "Honiara", capital_cn: "霍尼亚拉", region_en: "Oceania", region_cn: "大洋洲", subregion_en: "Melanesia", subregion_cn: "美拉尼西亚", flag: "🇸🇧" },
  "SOM": { name_en: "Somalia", name_cn: "索马里", capital_en: "Mogadishu", capital_cn: "摩加迪沙", region_en: "Africa", region_cn: "非洲", subregion_en: "Eastern Africa", subregion_cn: "东非", flag: "🇸🇴" },
  "ZAF": { name_en: "South Africa", name_cn: "南非", capital_en: "Pretoria", capital_cn: "比勒陀利亚", region_en: "Africa", region_cn: "非洲", subregion_en: "Southern Africa", subregion_cn: "南非", flag: "🇿🇦" },
  "SSD": { name_en: "S. Sudan", name_cn: "南苏丹", capital_en: "Juba", capital_cn: "朱巴", region_en: "Africa", region_cn: "非洲", subregion_en: "Eastern Africa", subregion_cn: "东非", flag: "🇸🇸" },
  "ESP": { name_en: "Spain", name_cn: "西班牙", capital_en: "Madrid", capital_cn: "马德里", region_en: "Europe", region_cn: "欧洲", subregion_en: "Southern Europe", subregion_cn: "南欧", flag: "🇪🇸" },
  "LKA": { name_en: "Sri Lanka", name_cn: "斯里兰卡", capital_en: "Colombo", capital_cn: "科伦坡", region_en: "Asia", region_cn: "亚洲", subregion_en: "Southern Asia", subregion_cn: "南亚", flag: "🇱🇰" },
  "SDN": { name_en: "Sudan", name_cn: "苏丹", capital_en: "Khartoum", capital_cn: "喀土穆", region_en: "Africa", region_cn: "非洲", subregion_en: "Northern Africa", subregion_cn: "北非", flag: "🇸🇩" },
  "SUR": { name_en: "Suriname", name_cn: "苏里南", capital_en: "Paramaribo", capital_cn: "帕拉马里博", region_en: "South America", region_cn: "南美洲", subregion_en: "South America", subregion_cn: "南美", flag: "🇸🇷" },
  "SWE": { name_en: "Sweden", name_cn: "瑞典", capital_en: "Stockholm", capital_cn: "斯德哥尔摩", region_en: "Europe", region_cn: "欧洲", subregion_en: "Northern Europe", subregion_cn: "北欧", flag: "🇸🇪" },
  "CHE": { name_en: "Switzerland", name_cn: "瑞士", capital_en: "Bern", capital_cn: "伯尔尼", region_en: "Europe", region_cn: "欧洲", subregion_en: "Western Europe", subregion_cn: "西欧", flag: "🇨🇭" },
  "SYR": { name_en: "Syria", name_cn: "叙利亚", capital_en: "Damascus", capital_cn: "大马士革", region_en: "Asia", region_cn: "亚洲", subregion_en: "Western Asia", subregion_cn: "西亚", flag: "🇸🇾" },
  "TWN": { name_en: "Taiwan", name_cn: "台湾", capital_en: "Taipei", capital_cn: "台北", region_en: "Asia", region_cn: "亚洲", subregion_en: "Eastern Asia", subregion_cn: "东亚", flag: "🇹🇼" },
  "TJK": { name_en: "Tajikistan", name_cn: "塔吉克斯坦", capital_en: "Dushanbe", capital_cn: "杜尚别", region_en: "Asia", region_cn: "亚洲", subregion_en: "Central Asia", subregion_cn: "中亚", flag: "🇹🇯" },
  "TZA": { name_en: "Tanzania", name_cn: "坦桑尼亚", capital_en: "Dodoma", capital_cn: "多多马", region_en: "Africa", region_cn: "非洲", subregion_en: "Eastern Africa", subregion_cn: "东非", flag: "🇹🇿" },
  "THA": { name_en: "Thailand", name_cn: "泰国", capital_en: "Bangkok", capital_cn: "曼谷", region_en: "Asia", region_cn: "亚洲", subregion_en: "South-Eastern Asia", subregion_cn: "东南亚", flag: "🇹🇭" },
  "TLS": { name_en: "Timor-Leste", name_cn: "东帝汶", capital_en: "Dili", capital_cn: "帝力", region_en: "Asia", region_cn: "亚洲", subregion_en: "South-Eastern Asia", subregion_cn: "东南亚", flag: "🇹🇱" },
  "TGO": { name_en: "Togo", name_cn: "多哥", capital_en: "Lome", capital_cn: "洛美", region_en: "Africa", region_cn: "非洲", subregion_en: "Western Africa", subregion_cn: "西非", flag: "🇹🇬" },
  "TTO": { name_en: "Trinidad and Tobago", name_cn: "特立尼达和多巴哥", capital_en: "Port of Spain", capital_cn: "西班牙港", region_en: "North America", region_cn: "北美洲", subregion_en: "Caribbean", subregion_cn: "加勒比", flag: "🇹🇹" },
  "TUN": { name_en: "Tunisia", name_cn: "突尼斯", capital_en: "Tunis", capital_cn: "突尼斯", region_en: "Africa", region_cn: "非洲", subregion_en: "Northern Africa", subregion_cn: "北非", flag: "🇹🇳" },
  "TUR": { name_en: "Turkey", name_cn: "土耳其", capital_en: "Ankara", capital_cn: "安卡拉", region_en: "Asia", region_cn: "亚洲", subregion_en: "Western Asia", subregion_cn: "西亚", flag: "🇹🇷" },
  "TKM": { name_en: "Turkmenistan", name_cn: "土库曼斯坦", capital_en: "Ashgabat", capital_cn: "阿什哈巴德", region_en: "Asia", region_cn: "亚洲", subregion_en: "Central Asia", subregion_cn: "中亚", flag: "🇹🇲" },
  "UGA": { name_en: "Uganda", name_cn: "乌干达", capital_en: "Kampala", capital_cn: "坎帕拉", region_en: "Africa", region_cn: "非洲", subregion_en: "Eastern Africa", subregion_cn: "东非", flag: "🇺🇬" },
  "UKR": { name_en: "Ukraine", name_cn: "乌克兰", capital_en: "Kyiv", capital_cn: "基辅", region_en: "Europe", region_cn: "欧洲", subregion_en: "Eastern Europe", subregion_cn: "东欧", flag: "🇺🇦" },
  "ARE": { name_en: "United Arab Emirates", name_cn: "阿联酋", capital_en: "Abu Dhabi", capital_cn: "阿布扎比", region_en: "Asia", region_cn: "亚洲", subregion_en: "Western Asia", subregion_cn: "西亚", flag: "🇦🇪" },
  "GBR": { name_en: "United Kingdom", name_cn: "英国", capital_en: "London", capital_cn: "伦敦", region_en: "Europe", region_cn: "欧洲", subregion_en: "Northern Europe", subregion_cn: "北欧", flag: "🇬🇧" },
  "USA": { name_en: "United States of America", name_cn: "美国", capital_en: "Washington, D.C.", capital_cn: "华盛顿", region_en: "North America", region_cn: "北美洲", subregion_en: "Northern America", subregion_cn: "北美", flag: "🇺🇸" },
  "URY": { name_en: "Uruguay", name_cn: "乌拉圭", capital_en: "Montevideo", capital_cn: "蒙得维的亚", region_en: "South America", region_cn: "南美洲", subregion_en: "South America", subregion_cn: "南美", flag: "🇺🇾" },
  "UZB": { name_en: "Uzbekistan", name_cn: "乌兹别克斯坦", capital_en: "Tashkent", capital_cn: "塔什干", region_en: "Asia", region_cn: "亚洲", subregion_en: "Central Asia", subregion_cn: "中亚", flag: "🇺🇿" },
  "VUT": { name_en: "Vanuatu", name_cn: "瓦努阿图", capital_en: "Port Vila", capital_cn: "维拉港", region_en: "Oceania", region_cn: "大洋洲", subregion_en: "Melanesia", subregion_cn: "美拉尼西亚", flag: "🇻🇺" },
  "VEN": { name_en: "Venezuela", name_cn: "委内瑞拉", capital_en: "Caracas", capital_cn: "加拉加斯", region_en: "South America", region_cn: "南美洲", subregion_en: "South America", subregion_cn: "南美", flag: "🇻🇪" },
  "VNM": { name_en: "Vietnam", name_cn: "越南", capital_en: "Hanoi", capital_cn: "河内", region_en: "Asia", region_cn: "亚洲", subregion_en: "South-Eastern Asia", subregion_cn: "东南亚", flag: "🇻🇳" },
  "ESH": { name_en: "W. Sahara", name_cn: "西撒哈拉", capital_en: "El Aaiun", capital_cn: "阿尤恩", region_en: "Africa", region_cn: "非洲", subregion_en: "Northern Africa", subregion_cn: "北非", flag: "🇪🇭" },
  "YEM": { name_en: "Yemen", name_cn: "也门", capital_en: "Sanaa", capital_cn: "萨那", region_en: "Asia", region_cn: "亚洲", subregion_en: "Western Asia", subregion_cn: "西亚", flag: "🇾🇪" },
  "ZMB": { name_en: "Zambia", name_cn: "赞比亚", capital_en: "Lusaka", capital_cn: "卢萨卡", region_en: "Africa", region_cn: "非洲", subregion_en: "Eastern Africa", subregion_cn: "东非", flag: "🇿🇲" },
  "ZWE": { name_en: "Zimbabwe", name_cn: "津巴布韦", capital_en: "Harare", capital_cn: "哈拉雷", region_en: "Africa", region_cn: "非洲", subregion_en: "Eastern Africa", subregion_cn: "东非", flag: "🇿🇼" },
  "ATA": { name_en: "Antarctica", name_cn: "南极洲", capital_en: "--", capital_cn: "--", region_en: "Antarctica", region_cn: "南极洲", subregion_en: "Antarctica", subregion_cn: "南极", flag: "🇦🇶" },
  "NCL": { name_en: "New Caledonia", name_cn: "新喀里多尼亚", capital_en: "Noumea", capital_cn: "努美阿", region_en: "Oceania", region_cn: "大洋洲", subregion_en: "Melanesia", subregion_cn: "美拉尼西亚", flag: "🇳🇨" },
  "PSE": { name_en: "Palestine", name_cn: "巴勒斯坦", capital_en: "Ramallah", capital_cn: "拉姆安拉", region_en: "Asia", region_cn: "亚洲", subregion_en: "Western Asia", subregion_cn: "西亚", flag: "🇵🇸" },
  "KOS": { name_en: "Kosovo", name_cn: "科索沃", capital_en: "Pristina", capital_cn: "普里什蒂纳", region_en: "Europe", region_cn: "欧洲", subregion_en: "Southern Europe", subregion_cn: "南欧", flag: "🇽🇰" },
  "SDS": { name_en: "South Sudan", name_cn: "南苏丹", capital_en: "Juba", capital_cn: "朱巴", region_en: "Africa", region_cn: "非洲", subregion_en: "Eastern Africa", subregion_cn: "东非", flag: "🇸🇸" },
  "SOL": { name_en: "Somaliland", name_cn: "索马里兰", capital_en: "Hargeisa", capital_cn: "哈尔格萨", region_en: "Africa", region_cn: "非洲", subregion_en: "Eastern Africa", subregion_cn: "东非", flag: "🏳️" },
};

// UI translations
const UI_STRINGS = {
  en: {
    title: "HISTORY ATLAS",
    search: "Search countries...",
    population: "POPULATION",
    capital: "CAPITAL",
    region: "REGION",
    subregion: "SUBREGION",
    gdp: "GDP (USD MILLIONS)",
    economy: "ECONOMY",
    histPop: "HISTORICAL POPULATION",
    noData: "No data",
    world: "WORLD",
    scale: "scale",
    era: "ERA",
  },
  cn: {
    title: "历史地图",
    search: "搜索国家...",
    population: "人口",
    capital: "首都",
    region: "大洲",
    subregion: "区域",
    gdp: "GDP（百万美元）",
    economy: "经济分类",
    histPop: "历史人口",
    noData: "暂无数据",
    world: "全球",
    scale: "比例",
    era: "时代",
  }
};
