// ===== Historical Events =====
// Major events that appear on the timeline and as map annotations
const HISTORICAL_EVENTS = [
    // Ancient
    { year: -3000, title: 'Rise of Civilization', titleZh: '文明崛起', desc: 'Egypt, Mesopotamia, Indus Valley civilizations flourish', descZh: '埃及、美索不达米亚、印度河文明繁荣', icon: '🏛️', type: 'era' },
    { year: -2500, title: 'Great Pyramids Built', titleZh: '大金字塔建成', desc: 'Giza pyramids constructed under Pharaoh Khufu', descZh: '法老胡夫下令建造吉萨金字塔', icon: '△', type: 'build' },
    { year: -1200, title: 'Bronze Age Collapse', titleZh: '青铜时代崩溃', desc: 'Civilizations across Mediterranean collapse simultaneously', descZh: '地中海沿岸文明同时崩溃', icon: '⚔', type: 'collapse' },
    { year: -500, title: 'Classical Age Begins', titleZh: '古典时代开启', desc: 'Greek democracy, Buddha, Confucius — the Axial Age', descZh: '希腊民主、佛陀、孔子 -- 轴心时代', icon: '📜', type: 'era' },
    { year: -334, title: 'Alexander Conquers', titleZh: '亚历山大征服', desc: 'Alexander the Great creates largest empire yet', descZh: '亚历山大大帝建立迄今最大帝国', icon: '⚔', type: 'war' },
    { year: -221, title: 'Qin Unifies China', titleZh: '秦统一中国', desc: 'Qin Shi Huang unifies China, builds Great Wall', descZh: '秦始皇统一六国，修建长城', icon: '🏯', type: 'era' },
    { year: -27, title: 'Roman Empire Founded', titleZh: '罗马帝国建立', desc: 'Augustus becomes first Roman Emperor', descZh: '奥古斯都成为首任罗马皇帝', icon: '🏛️', type: 'era' },
    { year: 1, title: 'Year 1 CE', titleZh: '公元元年', desc: 'World population ~230 million. Han China & Roman Empire dominate', descZh: '世界人口约2.3亿，汉朝与罗马帝国称霸', icon: '📅', type: 'milestone' },
    { year: 200, title: 'Han Dynasty Falls', titleZh: '汉朝灭亡', desc: 'China fragments into Three Kingdoms era', descZh: '中国进入三国时代', icon: '⚔', type: 'collapse' },
    { year: 476, title: 'Fall of Rome', titleZh: '罗马灭亡', desc: 'Western Roman Empire falls — Dark Ages begin in Europe', descZh: '西罗马帝国灭亡，欧洲进入黑暗时代', icon: '💀', type: 'collapse' },
    { year: 632, title: 'Islamic Expansion', titleZh: '伊斯兰扩张', desc: 'After Muhammad, Arab conquests reshape the world', descZh: '穆罕默德之后，阿拉伯征服重塑世界', icon: '☪', type: 'era' },
    { year: 700, title: 'Tang Golden Age', titleZh: '唐朝盛世', desc: 'Tang Dynasty China — peak of arts, trade, and power', descZh: '唐朝中国 -- 艺术、贸易、国力巅峰', icon: '✨', type: 'era' },
    { year: 800, title: 'Charlemagne Crowned', titleZh: '查理曼加冕', desc: 'Holy Roman Empire founded, Europe slowly rebuilds', descZh: '神圣罗马帝国建立，欧洲缓慢复兴', icon: '👑', type: 'era' },
    { year: 1000, title: 'Song Dynasty Peak', titleZh: '宋朝鼎盛', desc: 'World\'s most advanced economy — gunpowder, printing, compass', descZh: '世界最先进经济体 -- 火药、印刷、指南针', icon: '✨', type: 'era' },
    { year: 1206, title: 'Mongol Empire Rises', titleZh: '蒙古帝国崛起', desc: 'Genghis Khan unites Mongols — largest land empire ever', descZh: '成吉思汗统一蒙古 -- 史上最大陆地帝国', icon: '🏇', type: 'war' },
    { year: 1347, title: 'The Black Death', titleZh: '黑死病', desc: 'Bubonic plague kills 30-60% of Europe\'s population', descZh: '鼠疫杀死欧洲30-60%人口', icon: '☠', type: 'plague' },
    { year: 1405, title: 'Zheng He Voyages', titleZh: '郑和下西洋', desc: 'China\'s treasure fleet explores Indian Ocean', descZh: '中国宝船队探索印度洋', icon: '⛵', type: 'explore' },
    { year: 1453, title: 'Constantinople Falls', titleZh: '君士坦丁堡陷落', desc: 'Ottoman conquest ends Byzantine Empire', descZh: '奥斯曼征服终结拜占庭帝国', icon: '⚔', type: 'war' },
    { year: 1492, title: 'Columbus Reaches Americas', titleZh: '哥伦布到达美洲', desc: 'European colonization of the New World begins', descZh: '欧洲殖民新大陆开始', icon: '⛵', type: 'explore' },
    { year: 1500, title: 'Age of Exploration', titleZh: '大航海时代', desc: 'Portugal, Spain, and soon all of Europe expand globally', descZh: '葡萄牙、西班牙及欧洲开始全球扩张', icon: '🌍', type: 'era' },
    { year: 1600, title: 'East India Companies', titleZh: '东印度公司', desc: 'Corporate colonialism — Dutch & British EICs founded', descZh: '公司殖民主义 -- 荷兰与英国东印度公司成立', icon: '💰', type: 'era' },
    { year: 1687, title: 'Newton\'s Principia', titleZh: '牛顿原理', desc: 'Scientific Revolution transforms European thought', descZh: '科学革命改变欧洲思想', icon: '🔬', type: 'science' },
    { year: 1760, title: 'Industrial Revolution', titleZh: '工业革命', desc: 'Britain industrializes — the Great Divergence begins', descZh: '英国工业化 -- 大分流开始', icon: '⚙', type: 'era' },
    { year: 1776, title: 'American Independence', titleZh: '美国独立', desc: 'United States declares independence from Britain', descZh: '美国宣布脱离英国独立', icon: '🗽', type: 'era' },
    { year: 1789, title: 'French Revolution', titleZh: '法国大革命', desc: 'Monarchy falls — reshapes European politics forever', descZh: '君主制倒台，永远改变欧洲政治', icon: '⚔', type: 'war' },
    { year: 1815, title: 'Waterloo', titleZh: '滑铁卢', desc: 'Napoleon defeated. Britain becomes global hegemon', descZh: '拿破仑战败，英国成为全球霸主', icon: '⚔', type: 'war' },
    { year: 1839, title: 'Opium Wars Begin', titleZh: '鸦片战争', desc: 'Britain forces open China — Century of Humiliation begins', descZh: '英国强迫中国开放 -- 百年屈辱开始', icon: '⚔', type: 'war' },
    { year: 1861, title: 'US Civil War', titleZh: '美国内战', desc: '750,000 dead — slavery abolished, Union preserved', descZh: '75万人死亡，废除奴隶制，联邦保全', icon: '⚔', type: 'war' },
    { year: 1868, title: 'Meiji Restoration', titleZh: '明治维新', desc: 'Japan rapidly modernizes — becomes Asian superpower', descZh: '日本快速现代化，成为亚洲强国', icon: '🏯', type: 'era' },
    { year: 1914, title: 'World War I', titleZh: '第一次世界大战', desc: '20 million dead. Empires fall. Modern world begins', descZh: '2000万人死亡，帝国崩塌，现代世界开始', icon: '💀', type: 'war' },
    { year: 1918, title: 'Spanish Flu', titleZh: '西班牙流感', desc: '50-100 million dead worldwide — deadliest pandemic', descZh: '全球5000万-1亿人死亡 -- 最致命大流行', icon: '☠', type: 'plague' },
    { year: 1929, title: 'Great Depression', titleZh: '大萧条', desc: 'Global economic collapse — 25% unemployment in US', descZh: '全球经济崩溃，美国失业率25%', icon: '📉', type: 'collapse' },
    { year: 1939, title: 'World War II', titleZh: '第二次世界大战', desc: '70-85 million dead. Holocaust. Atomic bombs. World reshaped', descZh: '7000-8500万人死亡，大屠杀，原子弹，世界重塑', icon: '💀', type: 'war' },
    { year: 1945, title: 'UN Founded / Cold War Begins', titleZh: '联合国成立/冷战开始', desc: 'US & USSR emerge as superpowers. Nuclear age begins', descZh: '美苏成为超级大国，核时代开始', icon: '☢', type: 'era' },
    { year: 1947, title: 'India Independence', titleZh: '印度独立', desc: 'British India partitioned — India & Pakistan born', descZh: '英属印度分治，印度与巴基斯坦诞生', icon: '🏴', type: 'era' },
    { year: 1949, title: 'PRC Founded', titleZh: '新中国成立', desc: 'Mao proclaims People\'s Republic of China', descZh: '毛泽东宣告中华人民共和国成立', icon: '⭐', type: 'era' },
    { year: 1957, title: 'Sputnik / Space Age', titleZh: '人造卫星/太空时代', desc: 'USSR launches first satellite — space race begins', descZh: '苏联发射首颗卫星，太空竞赛开始', icon: '🛰', type: 'science' },
    { year: 1969, title: 'Moon Landing', titleZh: '登月', desc: 'Apollo 11 — humanity walks on the Moon', descZh: '阿波罗11号，人类踏上月球', icon: '🌙', type: 'science' },
    { year: 1978, title: 'China Opens Up', titleZh: '改革开放', desc: 'Deng Xiaoping launches economic reforms', descZh: '邓小平启动经济改革', icon: '📈', type: 'era' },
    { year: 1989, title: 'Berlin Wall Falls', titleZh: '柏林墙倒塌', desc: 'Cold War ends — Soviet bloc collapses', descZh: '冷战结束，苏联集团崩溃', icon: '🧱', type: 'era' },
    { year: 1991, title: 'USSR Dissolves', titleZh: '苏联解体', desc: 'US becomes sole superpower. 15 new nations born', descZh: '美国成为唯一超级大国，15个新国家诞生', icon: '💀', type: 'collapse' },
    { year: 2001, title: '9/11 & War on Terror', titleZh: '9/11与反恐战争', desc: 'September 11 attacks reshape global security', descZh: '9/11袭击重塑全球安全格局', icon: '⚔', type: 'war' },
    { year: 2008, title: 'Global Financial Crisis', titleZh: '全球金融危机', desc: 'Lehman Brothers collapses — worst crisis since 1929', descZh: '雷曼兄弟倒闭，1929年以来最严重危机', icon: '📉', type: 'collapse' },
    { year: 2020, title: 'COVID-19 Pandemic', titleZh: '新冠疫情', desc: 'Global pandemic — 7 million+ dead, world locked down', descZh: '全球大流行，700万+死亡，世界封锁', icon: '☠', type: 'plague' },
    { year: 2022, title: 'Ukraine War / AI Boom', titleZh: '乌克兰战争/AI爆发', desc: 'Russia invades Ukraine. ChatGPT launches AI revolution', descZh: '俄罗斯入侵乌克兰，ChatGPT引爆AI革命', icon: '⚡', type: 'era' },
];

// Event type colors
const EVENT_COLORS = {
    era: '#38bdf8',
    war: '#ef4444',
    collapse: '#f97316',
    plague: '#a855f7',
    explore: '#22d3ee',
    science: '#10b981',
    build: '#fbbf24',
    milestone: '#94a3b8',
};
